# Generated by Django 4.0.4 on 2022-04-21 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='text',
        ),
        migrations.AddField(
            model_name='note',
            name='attachments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='someone', max_length=255),
            preserve_default=False,
        ),
    ]
